[build]
  base = "/"
  publish = "frontend/build" 
  command = "cd frontend && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
